### ISSUE TITLE
postgres: return on insert

### ISSUE THREAD

**Issue by mren** [snd/mohair#12]
postgres supports a return on insert [http://www.postgresql.org/docs/8.4/static/sql-insert.html]

``` sql
INSERT INTO "foo" (id) VALUES (DEFAULT) RETURNING id;
```

mohair.insert has a third value `options` which is not used at all

**Comment by snd** [comment]
this is possible from version 0.6.2 on:

``` coffeescript
m.insert 'foo', {
    id: -> m.raw "DEFAULT"
}, -> m.raw " RETURNING id"
```
