### ISSUE TITLE
[Feature Request] allow using criterion on joins

### ISSUE THREAD

**Issue by tsouza** [snd/mohair#18]
Hi,

This would be nice:

```
query.join("inner join other", { "table.id": "other.id", "other.column": { $null: true }});
```

Cheers

**Comment by snd** [comment]
Hi Thiago,

please excuse that i hesitate a bit to add new features to mohair:
my goal is to keep mohair small and focused. it should make it very easy to generate
sql for the most common queries. it's not my goal to make it generate every possible sql query.

there are already two ways to achieve what you want.

you can put the predicate into the where clause and use a criterion there:

``` coffeescript
query
    .join("INNER JOIN other ON table.id = other.id")
    .where("other.column": {$null: true})
```

http://stackoverflow.com/questions/1018952/condition-within-join-or-where

or you can put the predicate into the join (without using criterion):

``` coffeescript
query.join("INNER JOIN other ON table.id = other.id AND other.column IS NULL")
```

if you really need to use criterion to generate join conditions then i could add support for the following syntax:

``` coffeescript
query.join(
    "INNER JOIN other ON table.id = other.id"
    {"other.column": {$null: true}} # can be any criterion
)
```

which would generate this sql for the join:

``` sql
INNER JOIN other ON table.id = other.id AND other.column IS NULL
```

please tell me what you think about that.

**Comment by tsouza** [comment]
Hi,

I understand that I can use where to filter the join, but sometimes, filtering directly on the join statement produces a different query plan. And so, adding support to criterion on join predicate would give much more flexibility to query builder.

Your syntax proposal is actually what I had in mind.

Cheers

**Comment by snd** [comment]
version 0.8.4 has support for criteria for join predicates
