### ISSUE TITLE
parameters for select

### ISSUE THREAD

**Issue by mren** [snd/mohair#22]
Sometimes one needs parameters in a select query. For example in a Subquery as a column

``` sql
SELECT one.*, (SELECT count(1) FROM has_many WHERE has_many.one_id = id AND state = $state) as partial_count FROM one;
```

Currently it is not possible to use the proper escaped node-pg params in combination with mohair if a subquery with a param is needed

It would be great if we can use params in the select like this

``` coffeescript

subselect = "SELECT count(1) FROM has_many WHERE has_many.one_id = id AND state = ?"
mesa
  .select("one.*, (#{subselect}) as partial_count", state)
  .find cb
```

This would resemble the `where` interface

``` coffeescript
query = user.where(id: 3).where('name = ?', 'foo').select()
```

What do you think?

**Comment by snd** [comment]
the above no longer works as of version 0.11.0 which has real support for subqueries:

https://github.com/snd/mohair#select-with-subquery
https://github.com/snd/mohair#select
