### ISSUE TITLE
Adding UNION

### ISSUE THREAD

**Issue by mren** [snd/mohair#32]
Any plans on adding `UNION`

How should I translate this sql query to mohair

``` sql
SELECT 1 UNION SELECT 2;
```

**Comment by snd** [comment]
`UNION [ALL]`, `INTERSECT [ALL]` and `EXCEPT [ALL]` [are already in the dev branch](https://github.com/snd/mohair/blob/0af173775cfe237b9a59fe4c91150ae5b3aca798/src/mohair.coffee#L421) and definitely in release `0.13.0` :)

**Comment by snd** [comment]
``` js
mohair.select('1').union(mohair.select('2')).sql(); // -> 'SELECT 1 UNION SELECT 2'
```
